"""Add code_bill to Bill

Revision ID: c7cb4b616f4e
Revises: 
Create Date: 2024-08-07 18:07:40.161384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7cb4b616f4e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bill', sa.Column('code_bill', sa.String(length=50), nullable=False))
    op.add_column('bill', sa.Column('date', sa.DateTime(), nullable=False))
    op.add_column('bill', sa.Column('type_custommer', sa.String(length=255), nullable=True))
    op.add_column('bill', sa.Column('totalprice', sa.Integer(), nullable=True))
    op.add_column('bill', sa.Column('discount', sa.Integer(), nullable=True))
    op.add_column('bill', sa.Column('afterdiscount', sa.Integer(), nullable=True))
    op.add_column('bill', sa.Column('customerpaid', sa.Integer(), nullable=True))
    op.alter_column('bill', 'id_bill',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('bill', 'groupproduct')
    op.drop_column('bill', 'price')
    op.drop_column('bill', 'barcode')
    op.drop_column('bill', 'costcapital')
    op.drop_column('bill', 'nameproduct')
    op.drop_column('bill', 'path_image')
    op.drop_column('bill', 'inventory')
    op.drop_column('bill', 'brand')
    op.drop_column('bill', 'unit')
    op.drop_column('bill', 'plu')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bill', sa.Column('plu', sa.VARCHAR(length=50), nullable=False))
    op.add_column('bill', sa.Column('unit', sa.VARCHAR(length=50), nullable=False))
    op.add_column('bill', sa.Column('brand', sa.VARCHAR(length=255), nullable=True))
    op.add_column('bill', sa.Column('inventory', sa.INTEGER(), nullable=False))
    op.add_column('bill', sa.Column('path_image', sa.VARCHAR(length=255), nullable=True))
    op.add_column('bill', sa.Column('nameproduct', sa.VARCHAR(length=255), nullable=True))
    op.add_column('bill', sa.Column('costcapital', sa.INTEGER(), nullable=False))
    op.add_column('bill', sa.Column('barcode', sa.VARCHAR(length=50), nullable=False))
    op.add_column('bill', sa.Column('price', sa.INTEGER(), nullable=False))
    op.add_column('bill', sa.Column('groupproduct', sa.VARCHAR(length=255), nullable=True))
    op.alter_column('bill', 'id_bill',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('bill', 'customerpaid')
    op.drop_column('bill', 'afterdiscount')
    op.drop_column('bill', 'discount')
    op.drop_column('bill', 'totalprice')
    op.drop_column('bill', 'type_custommer')
    op.drop_column('bill', 'date')
    op.drop_column('bill', 'code_bill')
    # ### end Alembic commands ###
